name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - uses: jdx/mise-action@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          install: true
          cache: true

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run build

      - name: Test
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run test

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
          NPM_CONFIG__AUTHTOKEN: ${{ secrets.NPM_TOKEN }}
